baseURL = 'http://example.org/'
languageCode = 'es-es'
title = 'El blog de Johanna'
theme = 'tale'

[menu]
  [[menu.main]]
	identifier = "contacto"
	name = "Contacto"
	title = "Contacto"
	url = "/contacto/"
	weight = 2
  [[menu.main]]
	identifier = "noticias"
	name = "Noticias"
	title = "Noticias"
	url = "/noticias/"
	weight = 3
   [[menu.main]]
	identifier = "ubicaci贸n"
	name = "Ubicaci贸n"
	title = "Ubicaci贸n"
	url = "/ ubicaci贸n/"
	weight = 3
	[[menu.main]]
	identifier = "formulario"
	name = "Formulario"
	title = "Formulario"
	url = "/formulario/"
	weight = 3

[outputs]
  home = ["HTML", "JSON"]

[Params]
css = ["custom.css"]